### ISSUE TITLE
Missing rules handled by Prettier in index.js

### ISSUE THREAD

**Issue by tenretC** [shannonmoeller/stylelint-config-prettier#10]
I've found these rules that are handled by Prettier. Should we add them to the index.js file ?
Rules :

- number-no-trailing-zeros
- unit-case
- property-case
- selector-pseudo-class-case
- selector-pseudo-element-case
- selector-max-empty-lines
- media-feature-name-case
- at-rule-name-case
- no-extra-semicolons

**Comment by shannonmoeller** [comment]
That would be awesome. You’re really rocking this package this week. Much appreciated. Make sure to add yourself to the contributors list in the package.json too!

**Comment by tenretC** [comment]
I'm pretty new with Angular, Npm, etc, so let me know if you see something wrong.
In fact I'm currently doing my internship and for the project I'm working on, I needed Prettier. And in this project we use Stylelint too so I found your package useful to avoid conflicts and my chief told me it would be interesting to have a script to check the rules in conflict. =)

So, I'll add this rules to the index.js and add myself to the contributors ;-)

**Comment by dsebastien** [comment]
I love to see open source in action ;-)

**Comment by shannonmoeller** [comment]
Resolved by #9.
