### ISSUE TITLE
max-line-length being null seems to bring some default value lower than prettier

### ISSUE THREAD

**Issue by wbern** [shannonmoeller/stylelint-config-prettier#6]
I'm using prettier-vscode that has eslint and stylelint integration.

When I format a .less file, it keeps going back and forth of the width of the lines, where prettier seems to prefer a certain width (likely the one enforced in my .prettierrc of `100`, and stylelint prefers another.

Since I have manually increased the width to 100 instead of the default 80 I assumed that I should just put 100 in the stylelintrc file, but it seems stylelint still prefers shorter lines than prettier.

I increased the max-line-length to 9999 leaving it entirely to the prettier extension to format line lengths, and only then I am getting consistent/same results after every format action (not hopping back and forth between short and long lines).

Is there any recommendation on how to deal with this, and optionally any insight on why this is happening? My workaround is fine, but was surprised I could not find an issue about this.

**Comment by shannonmoeller** [comment]
I haven't experienced this, but it sounds downright annoying. Can you provide a sample of the .less code for a test case?

**Comment by shannonmoeller** [comment]
Better yet, can you confirm whether this fixes it? `"max-line-length": null`

**Comment by wbern** [comment]
I'm sorry, I think I had some other crappy extension installed in vs code that kept trying to do its thing after prettier and stylelint was finished.

I'm gonna close this. Thanks anyway.

**Comment by shannonmoeller** [comment]
Ok! I think I'm going to set `"max-line-length": null` anyway as it makes sense when paired with prettier.
