### ISSUE TITLE
CLI helper tool

### ISSUE THREAD

**Issue by tenretC** [shannonmoeller/stylelint-config-prettier#7]
Is it planned to provide a CLI helper tool just as [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) and [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier#cli-helper-tool) ?

**Comment by shannonmoeller** [comment]
It wasn't, but can be.

**Comment by tenretC** [comment]
I'm working on that but I'm not really familiar with stylelint config files. I got problems to read the rules contained in it (to later compare them just like in the tslint-config-prettier project).

**Comment by tenretC** [comment]
I've just finished it. I'm still testing it and when it's done, I do a pull request so you can check the code ;

**Comment by shannonmoeller** [comment]
That's awesome! Thanks!
